blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.postwall, name='postwall'),
    path('post/', views.post, name='post'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('post/<int:post_id>/delete/', views.delete_post, name='delete_post'),
    path('post/<int:post_id>/delete/confirm/', views.delete_post_confirmation, name='delete_post_confirmation'),
    path('add_comment/<int:post_id>/', views.add_comment, name='add_comment'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('search/', views.search, name='search'),
    path('search/suggestions/', views.search_suggestions, name='search_suggestions'),
]

p4_postwall/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class ProfileManager(BaseUserManager):
    """
    Custom manager for the Profile model, extending the default UserManager
    to provide methods for creating user and superuser accounts.
    """

    def create_user(self, username, first_name, last_name, email, password=None, **extra_fields):
        """
        Creates and saves a regular user with the given
        username, first name, last name, email, and password.
        """

        # If an email address is provided;if not, raise an error
        if not email:
            raise ValueError('Email is required')

        # Normalize the email to ensure it is in a consistent format
        email = self.normalize_email(email)
        # Create a new user instance with the data below
        user = self.model(
            username = username,
            email  = email,
            first_name = first_name,
            last_name = last_name,
            **extra_fields
        )
        # Hash the user's password for security before saving
        user.set_password(password)
        # Save the user instance to the database
        user.save(using=self._db)
        # Return the newly created user instance
        return user


    def create_superuser(self, username, first_name, last_name, email, password=None, **extra_fields):
        """
        Creates and saves a superuser with the given username, first name,
        last name, email, and password, ensuring specific permissions are set.
        """

        # Set default values for superuser-specific fields
        extra_fields.setdefault('is_admin', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_active', True)

        # Check if the "is_admin", "is_staff" fields is set to True; raise an error if not
        if extra_fields.get('is_admin') is not True:
            raise ValueError('Superuser must have is_admin=True.')

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        # Call the create_user method to create the superuser
        return self.create_user(username, first_name, last_name, email, password, **extra_fields)


class Profile(AbstractBaseUser):
    """
    Custom user model that extends AbstractBaseUser to create a user profile
    with specific fields and behavior for authentication.
    """

    username          = models.CharField(max_length=50, unique=True)
    first_name        = models.CharField(max_length=50)
    last_name         = models.CharField(max_length=50)
    email             = models.EmailField(max_length=100, unique=True)
    profile_picture   = models.ImageField(blank=True, upload_to='profile/')
    date_joined       = models.DateTimeField(auto_now_add=True)
    last_login        = models.DateTimeField(auto_now=True)
    is_admin          = models.BooleanField(default=False)
    is_staff          = models.BooleanField(default=True)
    is_active         = models.BooleanField(default=True)
    is_inactive       = models.BooleanField(default=True)
    is_published      = models.BooleanField(default=True)

    # Specifies the field used for user login (email instead of username)
    USERNAME_FIELD    = 'email'
    # Required fields when creating a user
    REQUIRED_FIELDS   = ['username', 'first_name', 'last_name']

    # Custom manager for the Profile model
    objects = ProfileManager()

    def full_name(self):
        """
        Returns the full name of the user by combining first and last names.
        """
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        """
        String representation of the Profile instance, returning the email.
        """
        return self.email

    def has_perm(self, perm, obj=None):
        """
        Returns whether the user has a specific permission. If admin = Returns True
        """
        return self.is_admin

    def has_module_perms(self, add_label):
        """
        Returns whether the user has permissions for a given module.
        Returns True for all modules
        """
        return True

blog/models.py
from django.db import models
from django.utils import timezone
from accounts.models import Profile


class Post(models.Model):
    user            = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')
    title           = models.CharField(max_length=50)
    img             = models.ImageField(upload_to='img/posts', blank=True, null=True)
    content         = models.TextField()
    created_at      = models.DateTimeField(default=timezone.now)
    updated_at      = models.DateTimeField(auto_now=True)
    is_published    = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def short_content(self):
        return self.content[:100]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments', null=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    def __str__(self):
        return f'{self.user.username} - {self.text}'

accounts/forms.py
from django import forms
from .models import Profile


class RegistrationForm(forms.ModelForm):
    """
    For user registration, allowing users to enter their details and set a password.
    Includes fields for username, first name, last name, email, password, and password confirmation.
    Custom validation ensures the two passwords match.
    """

    # Define the password field with a password input widget
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Choose a strong password',
        'class': 'form-control',
    }))

    # Define the confirm password field with a password input widget
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Same as you just created'
    }))

    class Meta:
        # Specify the model to use
        model  = Profile
        # Define the fields to include in the form
        fields = ['username', 'first_name', 'last_name', 'email', 'password']

    def clean(self):
        """
        Custom validation method to ensure the password and confirm password fields match.
        Raises a ValidationError if they do not.
        """

        # Call the parent clean method
        cleaned_data = super(RegistrationForm, self).clean()
        # Get the password value
        password = cleaned_data.get('password')
        # Get the confirm password value
        confirm_password = cleaned_data.get('confirm_password')

        # If passwords match - confirm
        if password != confirm_password:
            # If not - raise validation error
            raise forms.ValidationError(
                # Error message
                "Passwords do not match."
            )

    def __init__(self, *args, **kwargs):
        """
        Initializes the Form with custom attributes for form fields.

        This method is called when an instance of RegistrationForm is created.
        It allows us to set initial attributes such as placeholder text and CSS classes for each field.
        """

        # Call the parent class's __init__ method to ensure that the form is properly initialized
        super(RegistrationForm, self).__init__(*args, **kwargs)

        # Set placeholder text for the fields to guide the user
        self.fields['username'].widget.attrs['placeholder'] = 'Hoffmeister'
        self.fields['first_name'].widget.attrs['placeholder'] = 'David'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Hasselhoff'
        self.fields['email'].widget.attrs['placeholder'] = 'David.Hasselhoff@hotmail.com'

        # Loop through all fields in the form to add a CSS class for styling
        for field in self.fields:
            # Add the 'form-control' class to each field to apply Bootstrap styling
            self.fields[field].widget.attrs['class'] = 'form-control'


class UserForm(forms.ModelForm):
    """
    For updating user profile information incl. first name, last name, email, username and profile picture.
    """

    class Meta:
        # Specify the model that the form is associated with
        model = Profile
        # Define the fields that will be included in the form
        fields = ['first_name', 'last_name', 'email', 'username', 'profile_picture']

templates/alerts.html
<div class="alert-c">
	{% for message in messages %}
		<div class="alert alert-success fade show" role="alert">{{ message }}</div>
	{% endfor %}
</div>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Meta -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <!-- Title -->
    <title>{% block title %} Post Wall {% endblock %}</title>

    <!-- Bootstrap Css -->
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        crossorigin="anonymous"
    />

    <!-- Base Css -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css"/>
    {% block extra_css %}{% endblock %}

    <!-- jQuery Script -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" crossorigin="anonymous"></script>

    <!-- Bootstrap Bundle & Popper Script -->
    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous">
    </script>

    <!-- Font Awesome Script -->
    <script src="https://kit.fontawesome.com/6f8277bec5.js" crossorigin="anonymous"></script>

    <!-- Custom Scripts -->
    <script src="{% static 'js/alert.js' %}" defer></script>
    <script src="{% static 'js/navbar.js' %}" defer></script>
    <script src="{% static 'js/hide_search.js' %}" defer></script>
    <script src="{% static 'js/search.js' %}" defer></script>
    <script src="{% static 'js/comment.js' %}" defer></script>
    <script src="{% static 'js/scroll_to_post.js' %}"></script>
    <script src="{% static 'js/delete_confirmation.js' %}" defer></script>
    {% block extra_scripts %}{% endblock %}
</head>
<body>

    <!-- Navbar -->
    {% include 'navbar.html' %}

    <!-- Alert Messages -->
    {% include 'alerts.html' %}

    <!-- Content -->
    {% block content %}
        <!-- Child Templats -->
    {% endblock %}

    <!-- Footer -->
    {% include 'footer.html' %}

</body>
</html>

templates/change_password.html
{% extends 'base.html' %}

{% block title %} Postwall - Change Password {% endblock %}

{% block content %}
<div class="brickwall">
    <div class="item-container">
        {% include 'alerts.html' %}

        <div class="row">
            {% include 'dashboard_sidebar.html' %}

            <main class="col-md-7">
                <div class="leather">
                    <form action="{% url 'change_password' %}" method="POST">
                        {% csrf_token %}

                        <!-- Current Password -->
                        <div class="form-group">
                            <label class="form-label" for="id_current_password">
                                Current Password:
                            </label>
                            <input
                                type="password"
                                id="id_current_password"
                                name="current_password"
                                placeholder="Current Password"
                                class="form-control"
                                required aria-label="Current Password"
                            />
                        </div>

                        <!-- New Password -->
                        <div class="form-group">
                            <label class="form-label" for="id_new_password">
                                New Password:
                            </label>
                            <input
                                type="password"
                                id="id_new_password"
                                name="new_password"
                                placeholder="New Password"
                                class="form-control"
                                required aria-label="New Password"
                            />
                        </div>

                        <!-- Confirm Password -->
                        <div class="form-group">
                            <label class="form-label" for="id_confirm_password">
                                Confirm Password:
                            </label>
                            <input
                                type="password"
                                id="id_confirm_password"
                                name="confirm_new_password"
                                placeholder="Confirm New Password"
                                class="form-control"
                                required aria-label="Confirm New Password"
                            />
                        </div>

                        <!-- Submit Button -->
                        <div class="form-button-container">
                            <button type="submit" class="green-button">
                                Submit
                            </button>
                        </div>

                    </form>
                </div>
            </main>
        </div>
    </div>
</div>
{% endblock %}

templates/create_new_password.html
{% extends 'base.html' %}

{% block title %} Create New Password {% endblock %}

{% block content %}
<div class="brickwall">
    <div class="concrete">
        <div class="leather">
            {% include 'alerts.html' %}

            <div class="form-title">Create a New Password</div>
                <form action="{% url 'reset_password' uidb64=uidb64 token=token %}" method="POST">
                    {% csrf_token %}

                    <!-- New Password -->
                    <div class="form-group">
                        <label for="new_password">New Password:</label>
                        <input type="password" id="id_new_password" name="new_password"
                            class="form-control"required placeholder="Enter new password"
                            aria-label="New Password"
                        />
                    </div>

                    <!-- Confirm New Password -->
                    <div class="form-group">
                        <label for="confirm_new_password">Confirm New Password:</label>
                        <input type="password" id="id_confirm_new_password"
                            name="confirm_new_password" class="form-control"
                            required placeholder="Confirm new password"
                            aria-label="Confirm New Password"
                        />
                    </div>

                    <!-- Submit Button -->
                    <div class="form-button-container">
                        <button type="submit" class="button-1">Reset Password</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Postwall - Edit Profile {% endblock %}

{% block content %}
<div class="brickwall">
	<div class="item-container">
		{% include 'alerts.html' %}

		<div class="row">
			{% include 'dashboard_sidebar.html' %}

			<main class="col-md-7">
				<div class="leather">
					<div class="col-md-12">
						<div class="profile-picture-container">
							{% if user_form.instance.profile_picture %}
							<img
								class="profile-picture"
								src="{{ user_form.instance.profile_picture.url }}"
								alt="Profile Picture"
							/>
							{% endif %}
						</div>
						<form class="edit_profile-form" id="id_edit_profile"
							action="{% url 'edit_profile' %}" method="POST"
							enctype="multipart/form-data">
							{% csrf_token %}

							<!-- Profile Picture Upload -->
							<div class="form-group">
								<label class="form-label" for="id_profile_picture">
									Profile Picture:
								</label>
								{{ user_form.profile_picture }}
							</div>

							<hr/>

							<!-- First Name Field -->
							<div class="form-group">
								<label class="form-label" for="id_first_name">
									First Name:
								</label>
								<div class="edit_profile-fields">
									{{ user_form.first_name }}
								</div>
							</div>

							<!-- Last Name Field -->
							<div class="form-group">
								<label class="form-label" for="id_last_name">
									Last Name:
								</label>
								<div class="edit_profile-fields">
									{{ user_form.last_name }}
								</div>
							</div>

							<!-- Email Field -->
							<div class="form-group">
								<label class="form-label" for="id_email">
									Email:
								</label>
								<div class="edit_profile-fields">
									{{ user_form.email }}
								</div>
							</div>

							<!-- Username Field -->
							<div class="form-group">
								<label class="form-label" for="id_username">
									Username:
								</label>
								<div class="edit_profile-fields">
									{{ user_form.username }}
								</div>
							</div>

							<!-- Submit Button -->
							<div class="form-button-container">
								<button type="submit" class="green-button">
									Update
								</button>
							</div>

						</form>
					</div>
				</div>
			</main>
		</div>
	</div>
</div>
{% endblock %}

templates/footer.html
{% load static %}

{% block content %}
<footer class="developer">
    Author: Glenn .J &copy; {{ current_year }}
</footer>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="brickwall">
    <div class="concrete">
        <div class="leather">
            <div class="login-container">
                {% if request.GET.command == 'verification' %}
                    <!-- Verification message container -->
                    <div class="container mx-auto alert alert-info text-center" role="alert">
                        Please verify your account by clicking on the link in the email
                        we have just sent to
                        [{{ request.GET.email }}]
                        <a href="{% url 'login' %}">Login</a>
                    </div>
                {% else %}

                    <!-- Login form title -->
                    <div class="form-title">Login</div>
                    {% include 'alerts.html' %}

                    <!-- Login form -->
                    <form class="login-form" method="POST" action="{% url 'login' %}">
                        {% csrf_token %}

                        <!-- Email input -->
                        <div class="form-group">
                            <label class="form-label" for="email">Email:</label>
                            <input
                                class="form-control"
                                id="id_email"
                                type="email"
                                placeholder="Your email address here"
                                name="email"
                            />
                        </div>

                        <!-- Password input -->
                        <div class="form-group">
                            <label class="form-label" for="password">Password:</label>
                            <input
                                class="form-control"
                                id="id_password"
                                type="password"
                                placeholder="Your password here"
                                name="password"
                            />
                        </div>

                        <!-- Forgot password link -->
                        <a class="smal-text" href="{% url 'request_password_reset' %}">
                            Forgot your Password?
                        </a>

                        <!-- Submit button -->
                        <div class="form-button-container">
                            <button type="submit" class="button-1">Submit</button>
                        </div>

                    </form>
                {% endif %}

            </div>
        </div>

        <!-- Registration prompt -->
        <div class="account-container">Don't have an Account?
            <a class="account" href="{% url 'register' %}">Register Here</a>
        </div>

    </div>
</div>
{% endblock %}

templates/navbar.html
{% load static %}

{% block extra_css %}
	<link href="{% static 'css/navbar.css' %}" rel="stylesheet" type="text/css"/>
{% endblock %}

{% block header %}
<header>
	<!-- Brand -->
	<nav class="navbar navbar-expand-lg">
		<div class="container-fluid">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="navbar-brand {% if request.path == '/postwall/' %} active {% endif %}"
						href="{% url 'postwall' %}">Post Wall</a>
				</li>
			</ul>

			<!-- Toggler -->
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
				data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
				aria-expanded="false" aria-label="Toggle navigation">
				{% if user.is_authenticated and profile_picture_url %}
					<img src="{{ profile_picture_url }}" alt="profile pic" class="profile-image-toggler"/>
				{% endif %}
				<i class="fas fa-chevron-down"></i>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<!-- Search Function -->
				<form action="{% url 'search' %}" method="GET" class="input-group ms-auto">
					<input type="text" name="keyword" class="form-control search-input"
						placeholder="Search for a Post" aria-label="Search" id="search-input"
						autocomplete="off"/>
					<button class="search-btn" type="submit" id="btn-search" aria-label="Search posts">
						<i class="fas fa-search"></i>
					</button>
					<div class="suggestions"></div>
				</form>

				<!-- Nav Links -->
				<ul class="navbar-nav ms-auto">
					<!-- Post Link -->
					<li class="nav-item">
						<a class="nav-link {% if request.resolver_match.url_name == '/post/' %} active {% endif %}"
							href="{% url 'post' %}">Post</a>
					</li>

					<!-- Message Link - Not Operational -->
					<li class="nav-item">
						<a class="nav-link {% if request.resolver_match.url_name == '/messages/' %} active {% endif %}"
							href="#">Messages</a>
					</li>

					<!-- Friends Link - Not Operational -->
					<li class="nav-item dropdown">
						<a class="nav-link {% if request.resolver_match.url_name == '/friends/' %} active {% endif %}"
							href="#">Friends</a>
					</li>

					<!-- Dropdown Link (Profile Dashboard) -->
					<li class="nav-item dropdown">
						<a class="nav-link {% if request.resolver_match.url_name == 'profile' %} active {% endif %}"
							href="{% if user.is_authenticated %}{% url 'dashboard' %}{% else %}{% url 'login' %}{% endif %}"
							id="profiledropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							{% if user.is_authenticated and profile_picture_url %}	
								<!-- Show profile picture in link when authenticated -->
								<span class="d-lg-none">
									<img src="{{ profile_picture_url }}" alt="profile pic" class="profile-image-toggler"/>
								</span>
								<!-- Show the profile picture when on large screens -->
								<span class="d-none d-lg-inline">
									<img src="{{ profile_picture_url }}" alt="profile pic" class="profile-image"/>
								</span>
							{% else %}
								<!-- Show profile text in both cases if there's an error -->
								<span class="d-lg-none">Profile</span>
								<span class="d-none d-lg-inline">Profile</span>
							{% endif %}
						</a>
						<ul class="dropdown-menu">
							{% if user.is_authenticated %}
								<li><a class="dropdown-item {% if request.resolver_match.url_name == 'dashboard' %} active {% endif %}" href="{% url 'dashboard' %}">Dashboard</a></li>
								<li><a class="dropdown-item {% if request.resolver_match.url_name == 'logout' %} active {% endif %}" href="{% url 'logout' %}">Logout</a></li>
							{% else %}
								<li><a class="dropdown-item {% if request.resolver_match.url_name == 'login' %} active {% endif %}" href="{% url 'login' %}">Login</a></li>
							{% endif %}
						</ul>
					</li>

				</ul>
			</div>
		</div>
	</nav>
</header>
{% endblock %}

{% block extra_scripts %}
	<!-- See scripts for description -->
    <script src="{% static 'js/navbar.js' %}"></script>
    <script src="{% static 'js/hide_search.js' %}"></script>
	<script src="{% static 'js/search.js' %}"></script>
{% endblock %}

templates/post.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	Postwall - Create a New Post
{% endblock %}
{% block content %}
<div class="brickwall">
	<div class="concrete">
		<div class="post-header">Create a New Post</div>
		<div class="post-form-container">
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}

				<!-- Title Field -->
				<div class="post-form">
					<label for="id_title" class="post-form-label">Title:</label>
					<input class="form-control" type="text" id="id_title" name="title"
						placeholder="Write your title here..."/>
				</div>

				<!-- Content Field -->
				<div class="post-form">
					<label for="id_content" class="post-form-label">Content:</label>
					<textarea class="form-control" id="id_content" name="content"
						rows="5" placeholder="Write your content here..."></textarea>
				</div>

				<!-- Image Field -->
				<div class="post-form">
					<label for="id_img" class="post-form-label">Image:</label>
					<input class="form-control" type="file" id="id_img" name="img"/>
				</div>

				<!-- Submit Button -->
				<div class="post-form-button-container">
					<button type="submit" class="green-button">Post</button>
				</div>

			</form>
		</div>
	</div>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="brickwall">
    <div class="concrete">
        <div class="leather">
            <div class="register-container">
                <div class="form-title">Register</div>

                <!-- Include alerts for error/success messages -->
                {% include 'alerts.html' %}

                <form class="register-form" action="{% url 'register' %}" method="POST">
                    {% csrf_token %}

                    <!-- First Name Field -->
                    <div class="form-group">
                        <label class="form-label" for="id_first_name">First Name:</label>
                        {{ form.first_name }}
                    </div>

                    <!-- Last Name Field -->
                    <div class="form-group">
                        <label class="form-label" for="id_last_name">Last Name:</label>
                        {{ form.last_name }}
                    </div>

                    <!-- Email Field -->
                    <div class="form-group">
                        <label class="form-label" for="id_email">Email:</label>
                        {{ form.email }}
                    </div>

                    <!-- Username Field -->
                    <div class="form-group">
                        <label class="form-label" for="id_username">Username:</label>
                        {{ form.username }}
                    </div>

                    <!-- Password Field -->
                    <div class="form-group">
                        <label class="form-label" for="id_password">Password:</label>
                        {{ form.password }}
                    </div>

                    <!-- Confirm Password Field -->
                    <div class="form-group">
                        <label class="form-label" for="id_confirm_password">Confirm Password:</label>
                        {{ form.confirm_password }}
                    </div>

                    <!-- Submit Button -->
                    <div class="form-button-container">
                        <button type="submit" class="button-1" aria-label="Submit registration form">
                            Submit
                        </button>
                    </div>

                    <!-- Displaying form errors -->
                    {{ form.email.errors }}
                    {{ form.non_field_errors }}
                </form>
            </div>
        </div>

        <!-- Link to Login if the user already has an account -->
        <div class="account-container">Have an Account?
            <a class="account" href="{% url 'login' %}">Login Here</a>
        </div>
    </div>
</div>
{% endblock %}

templates/request_password_reset.html
{% autoescape off %}
    <div style="text-align: center;">
        Hello <strong>{{ user.first_name }}</strong>!
        <br><br>
        To reset your password, click 
        <a href="http://{{ domain }}{% url 'create_new_password' uidb64=uid token=token %}" target="_blank" rel="noopener noreferrer">here</a>
        to set a new password.
        <br><br>
        If you didn't request this, please ignore this email.
    </div>
{% endautoescape %}

templates/reset_password.html
{% extends 'base.html' %}
{% block content %}
<div class="brickwall">
	<div class="concrete">
		<div class="leather">

			<!-- Include alerts for error/success messages -->
			{% include 'alerts.html' %}
			<div class="form-title">Dont remember your password?</div>

				<!-- Action for password reset -->
				<form action="{% url 'request_password_reset' %}" method="POST">
					{% csrf_token %}
					<div class="form-group">
						<p class="reset_password_guide">
							1. Enter Your Email Address.
							<br/>2. Click on the "Submit" Button below.
							<br/>3. Click on the link in the email we have sent to you.
						</p>
						<input type="email" id="id_email" name="email" class="form-control" required placeholder="Enter your email"/>
					</div>
					<div class="form-button-container">
						<button type="submit" class="button-1">Submit</button>
					</div>
				</form>
			</div>
		</div>

		<!-- If not registered -->
		<div class="account-container">Don't have an Account?
			<a class="account" href="{% url 'register' %}"> Register Here</a>
		</div>
	</div>
</div>
{% endblock %}